id: P005515
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:52.835021
source_metadata:
  id: bdr:W30047
  title: ཀུན་མཁྱེན་ཆོས་འབྱུང་གནས་ཀྱི་གསུང་རྒྱུན་དྲི་མ་མེད་པ་བུང་བའི་དགའ་སྟོན་དགེ་འདུན་ཉི་ཤུའི་རྣམ་གཞག
  author: ''
  volumes:
    e39d2d74c6204a2c9c1754649843b21e:
      image_group_id: I1KG10310
      title: ''
      volume_number: 1
      total_pages: 245
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
